import React,{useState,useRef} from 'react';
import {Row,parse,issues,duplicate,csvSample,kakaoSample,tsvSample,validDate,columns,headerKey,importHeaders,decodeImport,metaSample} from './model';
export function ImportDialog({rows,onClose,onApply}:{rows:Row[];onClose:()=>void;onApply:(r:Row[])=>Promise<void>}){
 const [saving,setSaving]=useState(false);
 const [text,setText]=useState('');const [draft,setDraft]=useState<Row[]|null>(null);const [selected,setSelected]=useState<string[]>([]);const [supplier,setSupplier]=useState('');const [date,setDate]=useState('');const [error,setError]=useState('');
 const [dragOver,setDragOver]=useState(false),[fileName,setFileName]=useState(''),[reading,setReading]=useState(false);const readId=useRef(0);
 async function readFiles(files:FileList|null){if(!files?.length)return;if(files.length!==1){setError('파일은 한 번에 하나씩 가져와 주세요.');return;}const f=files[0]!;if(!/\.(csv|tsv|txt)$/i.test(f.name)){setError('CSV·TSV·TXT 파일을 지원합니다. 엑셀 파일은 CSV로 저장하거나 셀을 복사해 붙여넣어 주세요.');return;}if(f.size>5*1024*1024){setError('5MB 이하 파일을 가져와 주세요.');return;}const id=++readId.current;setReading(true);setError('');try{const raw=decodeImport(await f.arrayBuffer());if(id!==readId.current)return;if(raw.includes('\uFFFD'))throw new Error('UTF-8 형식으로 저장한 파일을 사용해 주세요.');if(!raw.trim())throw new Error('빈 파일입니다. 내용을 확인해 주세요.');setText(raw.replace(/^\uFEFF/,''));setFileName(f.name);setMapping({});setDraft(null);}catch(e){if(id===readId.current)setError((e as Error).message||'파일을 읽지 못했습니다. 다시 선택해 주세요.');}finally{if(id===readId.current)setReading(false);}}
 const [mapping,setMapping]=useState<Record<number,string>>({});const headers=importHeaders(text);
 const [allowIncomplete,setAllowIncomplete]=useState(false);
 const corrected=(r:Row)=>({...r,supplier:r.supplier||supplier,date:r.date||date});
 const check=(r:Row)=>{const c=corrected(r);return duplicate(c,rows)||duplicate(c,(draft??[]).slice(0,(draft??[]).findIndex(d=>d.id===r.id)))?'중복 의심':issues(c)?'확인 필요':'신규';};
 function preview(){try{const list=parse(text,mapping);if(!list.length)throw new Error('붙여넣을 내용을 입력해 주세요.');setDraft(list);setSelected(list.filter(r=>!duplicate(r,rows)).map(r=>r.id));setError('');}catch(e){setError(String((e as Error).message));}}
 const eligible=(draft??[]).filter(r=>{const c=corrected(r);return selected.includes(r.id)&&(check(r)==='신규'||(allowIncomplete&&check(r)==='확인 필요'&&!!(c.company||c.owner)&&!!c.supplier&&validDate(c.date)));});
 return <div className="sheet-overlay"><section role="dialog" aria-modal="true" aria-label="DB 가져오기" className="sheet-dialog"><header className="flex items-center justify-between border-b p-4"><div><h2 className="text-base font-bold">DB 가져오기</h2><p className="text-xs text-slate-500">메타 CSV·엑셀·카카오톡 내용을 한 번에 정리하세요.</p></div><button className="sheet-btn" onClick={onClose}>닫기</button></header><div className={`sheet-dialog-body sheet-file-drop ${dragOver?"is-file-over":""}`} onDragOver={e=>{if(e.dataTransfer.types.includes("Files")){e.preventDefault();e.dataTransfer.dropEffect="copy";setDragOver(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragOver(false);}} onDrop={e=>{e.preventDefault();setDragOver(false);if(draft){setError("원문 수정으로 돌아간 뒤 파일을 놓아 주세요.");return;}void readFiles(e.dataTransfer.files);}}>
 {!draft?<><details className="sheet-import-examples"><summary>예시로 체험하기</summary><div className="flex flex-wrap gap-2 mb-3"><button className="sheet-btn" onClick={()=>{setText(metaSample);setMapping({});}}>메타 CSV 샘플</button><button className="sheet-btn" onClick={()=>{setText(csvSample);setMapping({});}}>CSV 샘플</button><button className="sheet-btn" onClick={()=>setText(tsvSample)}>엑셀 샘플</button><button className="sheet-btn" onClick={()=>setText(kakaoSample)}>카카오 샘플</button></div></details><div className="sheet-upload-row"><label className="sheet-btn cursor-pointer">파일 선택<input aria-label="파일 선택" type="file" accept=".csv,.tsv,.txt" className="sr-only" onChange={e=>{void readFiles(e.target.files);e.target.value="";}}/></label><span>파일을 이 영역에 끌어 놓거나 내용을 붙여넣으세요</span></div><div className="sheet-drop-hint"><strong>{dragOver?"여기에 놓아 주세요":"파일을 끌어다 놓으세요"}</strong><span>CSV · TSV · TXT / 최대 5MB</span>{(reading||fileName)&&<span role="status">{reading?"파일을 읽는 중…":`✓ ${fileName}`}</span>}</div><textarea disabled={reading} aria-label="DB 원문" className="sheet-input w-full" rows={10} value={text} onChange={e=>{setText(e.target.value);setMapping({});}} placeholder={'사업자명\t대표자\t전화번호\n또는 카카오 메시지의 항목: 값'}/>{headers.length>0&&<details className="sheet-import-mapping"><summary>열 연결 확인 · 자동 인식 {headers.filter((h,i)=>mapping[i]||(!(i in mapping)&&headerKey(h))).length}/{headers.length}</summary><p>연결하지 않은 항목은 DB 원본 메모에 보관합니다. 날짜는 원본에 표시된 날짜를 사용합니다.</p>{headers.map((h,i)=><label key={i}><span>{h}</span><select aria-label={`${h} 연결`} className="sheet-input" value={mapping[i]??headerKey(h)??''} onChange={e=>setMapping({...mapping,[i]:e.target.value})}><option value="">원본 메모에 보관</option>{columns.filter(c=>!c.auto&&c.key!=='result'&&c.key!=='next').map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label>)}</details>}<p className="text-xs text-slate-500 mt-2">카카오톡은 ‘항목: 값’과 빈 줄로 고객을 구분합니다.</p></>:<>
 <div className="flex flex-wrap items-end gap-3 mb-3"><label className="text-xs">DB 공급처<input aria-label="묶음 공급처" className="sheet-input block mt-1" value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="공급업체·유입처"/></label><label className="text-xs">유입일<input aria-label="묶음 유입일" type="date" className="sheet-input block mt-1" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><span className="text-xs text-slate-500">비어 있는 항목에 함께 적용합니다.</span></div>
 <div className="flex gap-3 text-xs mb-3">{['신규','중복 의심','확인 필요'].map(s=><span key={s} className="rounded bg-slate-100 px-2 py-1">{s} {draft.filter(r=>check(r)===s).length}</span>)}</div>
 <label className="flex items-center gap-2 text-xs mb-3"><input type="checkbox" checked={allowIncomplete} onChange={e=>setAllowIncomplete(e.target.checked)}/>연락처 미완성도 임시등록 · 이름, 공급처, 유입일은 필수</label><div className="overflow-x-auto"><table className="sheet-table"><thead><tr><th>선택</th><th>확인</th><th>사업자명</th><th>대표자</th><th>전화번호</th><th>필요자금</th><th>체납여부</th><th>유입일</th><th>DB 공급처</th><th>유입채널</th><th>원본 메모</th></tr></thead><tbody>{draft.map((r,i)=><tr key={r.id}><td><input aria-label={`가져오기 ${i+1} 선택`} type="checkbox" checked={selected.includes(r.id)} disabled={check(r)==='중복 의심'} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/></td><td><span className={check(r)==='신규'?'text-emerald-700':'text-amber-700'}>{check(r)}</span><div className="text-px-11 text-slate-500">{issues(corrected(r))}</div></td>{(['company','owner','phone','funds','arrears','date','supplier','channel','memo'] as const).map(k=><td key={k}>{k==='channel'?<select aria-label={`가져오기 ${i+1} channel`} className="sheet-input" value={r.channel} onChange={e=>setDraft(draft.map(d=>d.id===r.id?{...d,channel:e.target.value}:d))}><option>매입DB</option><option>직접생산</option></select>:<input aria-label={`가져오기 ${i+1} ${k}`} type={k==='date'?'date':'text'} className="sheet-input" value={r[k]} onChange={e=>setDraft(draft.map(d=>d.id===r.id?{...d,[k]:e.target.value}:d))}/>}</td>)}</tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">중복 업체는 제외됩니다. 빠진 정보만 채운 뒤 추가하세요.</p></>}
 {error&&<p role="alert" className="text-sm text-red-600 mt-3">{error}</p>}</div><footer className="flex items-center justify-between gap-2 border-t p-4"><span className="text-xs text-slate-500">추가한 업체는 컨택관리에도 표시됩니다.</span><div className="flex gap-2">{draft&&<button className="sheet-btn" onClick={()=>setDraft(null)}>원문 수정</button>}<button className="sheet-btn primary" disabled={saving||reading||(!!draft&&!eligible.length)} onClick={async()=>{if(!draft){preview();return;}setSaving(true);try{await onApply(eligible.map(corrected));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>{draft?`확인한 ${eligible.length}건 추가`:'내용 확인하기'}</button></div></footer></section></div>
}
