export type Row = { id:string; supplier:string; date:string; channel:string; company:string; owner:string; phone:string; biz:string; address:string; industry:string; credit:string; sales:string; arrears:string; funds:string; result:string; first:string; stage:string; next:string; memo:string };
export type Key = Exclude<keyof Row,'id'>;
export const columns: {key:Key;label:string;auto?:boolean;width:number}[] = [
{key:'supplier',label:'DB 공급처',width:118},{key:'date',label:'유입일',width:115},{key:'company',label:'사업자명',width:154},{key:'owner',label:'대표자',width:100},{key:'phone',label:'전화번호',width:143},{key:'result',label:'컨택결과',width:110},{key:'next',label:'다음 연락일',width:120},{key:'funds',label:'필요자금',width:125},{key:'first',label:'최초상담일',auto:true,width:122},{key:'stage',label:'현재상태',auto:true,width:122},{key:'channel',label:'유입채널',width:110},{key:'biz',label:'사업자등록번호',width:145},{key:'address',label:'주소',width:210},{key:'industry',label:'업종',width:115},{key:'credit',label:'신용점수·기관',width:135},{key:'sales',label:'매출·기준',width:150},{key:'arrears',label:'체납여부',width:105},{key:'memo',label:'상담메모',auto:true,width:220}];
export const defaults:Key[]=['supplier','date','company','owner','phone','result','first','stage'];
export const blank = ():Row => ({id:crypto.randomUUID(),supplier:'',date:'',channel:'매입DB',company:'',owner:'',phone:'',biz:'',address:'',industry:'',credit:'',sales:'',arrears:'미확인',funds:'',result:'미컨택',first:'',stage:'미컨택',next:'',memo:''});
const aliases:Record<string,Key>={'디비업체':'supplier','공급처':'supplier','DB공급처':'supplier','유입일':'date','날짜':'date','업체명':'company','사업자명':'company','상호':'company','대표자':'owner','이름':'owner','전화':'phone','연락처':'phone','전화번호':'phone','사업자등록번호':'biz','주소':'address','업종':'industry','신용점수':'credit','신용점수·기관':'credit','매출':'sales','매출·기준':'sales','체납':'arrears','체납여부':'arrears','필요자금':'funds','메모':'memo','한줄메모':'memo','유입채널':'channel'};
export function delimited(text:string):string[][] {const out:string[][]=[];let row:string[]=[];let cell='';let quoted=false;const first=text.split('\n')[0]||'';const sep=first.includes('\t')?'\t':first.includes(',')?',':';';for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===sep||c==='\n')){row.push(cell.trim());cell='';if(c==='\n'){if(row.some(Boolean))out.push(row);row=[];}}else if(c!=='\r')cell+=c;}row.push(cell.trim());if(row.some(Boolean))out.push(row);if(quoted)throw new Error('닫히지 않은 CSV 따옴표를 확인해 주세요.');return out;}
export const headerKey=(s:string):Key|undefined=>{const name=s.replace(/^\uFEFF/,'').toLowerCase().replace(/[\s_?？:：-]/g,'');return ({fullname:'owner',name:'owner',phonenumber:'phone',phone:'phone',mobilephone:'phone',companyname:'company',company:'company',createdtime:'date',createdat:'date',streetaddress:'address',businessregistrationnumber:'biz',성함:'owner',성명:'owner',휴대폰번호:'phone',휴대전화번호:'phone',회사명:'company',신청일:'date',생성시간:'date',사업자명은:'company',대표자성함:'owner'} as Record<string,Key>)[name]||Object.entries(aliases).find(([k])=>k.toLowerCase().replace(/\s/g,'')===name)?.[1];};
export function importHeaders(text:string){try{const first=text.split('\n')[0]||'';return /[,\t;]/.test(first)?delimited(text)[0]||[]:[];}catch{return [];}}
export function decodeImport(bytes:ArrayBuffer){const b=new Uint8Array(bytes);const encoding=b[0]===255&&b[1]===254?'utf-16le':b[0]===254&&b[1]===255?'utf-16be':'utf-8';try{return new TextDecoder(encoding,{fatal:true}).decode(b).replace(/^\uFEFF/,'');}catch{throw new Error('파일 인코딩을 읽지 못했습니다. UTF-8 CSV로 저장해 주세요.');}}
export function parse(text:string,overrides:Record<number,string>={}):Row[]{if(!text.trim())return [];const headers=importHeaders(text);if(headers.length){const rows=delimited(text);const keys=headers.map((h,i)=>Object.prototype.hasOwnProperty.call(overrides,i)?overrides[i] as Key||undefined:headerKey(h));const meta=headers.some(h=>/^(ad_id|form_id|campaign_id|created_time|lead_id)$/i.test(h.trim()));if(!keys.some(Boolean))throw new Error('열 연결에서 이름·사업자명·전화번호 등 항목을 선택해 주세요.');const used=keys.filter(k=>k&&k!=='memo');if(new Set(used).size!==used.length)throw new Error('같은 항목에 여러 열이 연결됐습니다. 하나만 선택해 주세요.');return rows.slice(1).map(values=>{if(values.length!==headers.length)throw new Error('열 개수가 다른 행이 있습니다. CSV 원문을 확인해 주세요.');const r=blank();const notes:string[]=[];if(meta){r.supplier='메타 광고';r.channel='직접생산';}keys.forEach((k,i)=>{const v=values[i]||'';if(!v)return;if(!k||k==='memo'){notes.push(`${headers[i]}: ${v}`);return;}r[k]=v;if(k==='phone'){const cleaned=v.replace(/^p:/i,'').trim();r.phone=/^\+82/.test(cleaned)?'0'+cleaned.slice(3).replace(/^0/,'').replace(/[^0-9]/g,''):cleaned;}if(k==='date'){const date=v.match(/^(\d{4}-\d{2}-\d{2})(?:T|\s|$)/);r.date=date?date[1]!:v;}});r.memo=notes.join('\n');r.phone=formatPhone(r.phone);return r;});}return text.trim().split(/\n\s*\n/).map(block=>{const r=blank();for(const line of block.split('\n')){const match=line.match(/^\s*([^:：]+)[:：]\s*(.*)$/);if(match){const key=headerKey(match[1]!);if(key)r[key]=match[2]!.trim();}}if(!r.company&&!r.owner&&!r.phone)r.memo=block;r.phone=formatPhone(r.phone);return r;});}
export const metaSample='id,created_time,ad_id,form_id,platform,full_name,phone_number,company_name,필요자금,상담_희망시간\nlead_sample_1,2026-10-11T09:30:00+09:00,ad_sample,form_sample,fb,김가상,p:+821000004001,샘플 메타상사,5000만원,오후\nlead_sample_2,2026-10-11T10:00:00+09:00,ad_sample,form_sample,ig,이가상,+821000004002,샘플 메타공방,3000만원,오전';
export const norm=(s:string)=>s.replace(/[^0-9]/g,'');
export function duplicate(r:Row,existing:Row[]){return existing.some(e=>(r.biz&&norm(r.biz)===norm(e.biz))||(r.phone&&norm(r.phone)===norm(e.phone)&&r.owner.trim()===e.owner.trim()));}
export function validDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
export function issues(r:Row){return [!r.company&&!r.owner?'이름/사업자명':null,!/^0[0-9-]{8,14}$/.test(r.phone)?'전화번호':null,!validDate(r.date)?'유입일':null,!r.supplier?'공급처':null].filter(Boolean).join(' · ');}
export const csvSample='사업자명,대표자,전화번호,필요자금,체납여부\n샘플 달빛공방,한가상,010-0000-2001,"5,000만원",\n샘플 온유상사,김가상,010-0000-1001,3천만원,없음\n샘플 푸른제작,윤가상,확인 필요,,미확인';
export const kakaoSample='사업자명: 샘플 은하상사\n대표자: 조가상\n연락처: 010-0000-3001\n필요자금: 7천만원\n체납: 미확인\n\n사업자명: 샘플 별빛식품\n대표자: 오가상\n전화번호: 확인 필요';

export const tsvSample='사업자명\t대표자\t전화번호\t필요자금\t체납여부\n샘플 달빛공방\t한가상\t010-0000-2001\t5,000만원\t\n샘플 온유상사\t김가상\t010-0000-1001\t3천만원\t없음\n샘플 푸른제작\t윤가상\t확인 필요\t\t미확인';
export const outcomes=['미컨택','부재','단순거절','재통화','컨택진행','상담 후 거절'];
export function recordContact(row:Row,result:string,date:string):Row {
 const first=row.first||(['컨택진행','상담 후 거절'].includes(result)?date:'');
 return {...row,result,first,stage:['미컨택','상담 중'].includes(row.stage)?(first?'상담 중':'미컨택'):row.stage};
}

export const showsNextContact=(result:string)=>["부재","단순거절","상담 후 거절","재통화"].includes(result);

export function formatPhone(value:string){const raw=value.replace(/^p:/i,'').trim();const local=raw.startsWith('+82')?'0'+raw.slice(3).replace(/[^0-9]/g,'').replace(/^0/,''):raw;const digits=local.replace(/[^0-9]/g,'');if(/^01[016789]\d{8}$/.test(digits))return digits.replace(/^(\d{3})(\d{4})(\d{4})$/,'$1-$2-$3');if(/^02\d{7,8}$/.test(digits))return digits.replace(/^(02)(\d{3,4})(\d{4})$/,'$1-$2-$3');if(/^0[3-9]\d{8,9}$/.test(digits))return digits.replace(/^(\d{3})(\d{3,4})(\d{4})$/,'$1-$2-$3');return value;}
