import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import DesktopNav from '@/components/desktop/DesktopNav';
import TopHeader from '@/components/TopHeader';
import TabBar from '@/components/TabBar';
import PageContainer from '@/components/PageContainer';
import DirtyProvider from '@/components/DirtyGuard';
import {initial,Row,Key,columns,defaults,recordContact,blank,validDate,outcomes,formatPhone} from './model';
import {Grid} from './Grid';
import {ImportDialog} from './ImportDialog';
import {ContactDemo} from './ContactDemo';
import {DbDetail} from './DbDetail';
import {ContactDraft,contactDraft} from './ContactPanel';
const navigate=(path:string)=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));};
function App(){
 const [records,setRecords]=useState<Record<string,ContactDraft>>(()=>{try{return JSON.parse(sessionStorage.getItem('mock-db-contacts')||'{}');}catch{return {};}});
 useEffect(()=>{sessionStorage.setItem('mock-db-contacts',JSON.stringify(records));},[records]);
 const [draft,setDraft]=useState<Row|null>(null);
 const [path,setPath]=useState(location.pathname);
 const [rows,setRows]=useState<Row[]>(()=>{try{return (JSON.parse(sessionStorage.getItem('mock-db-rows')||'null')||initial).map((r:Row)=>({...r,phone:formatPhone(r.phone)}));}catch{return initial;}});
 const [visible,setVisible]=useState<Key[]>(()=>{try{return JSON.parse(localStorage.getItem('mock-db-v3-columns')||'null')||defaults;}catch{return defaults;}});
 const [filtersOpen,setFiltersOpen]=useState(false),[settings,setSettings]=useState(false),[importing,setImporting]=useState(false),[search,setSearch]=useState(''),[supplier,setSupplier]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[undo,setUndo]=useState<{rows:Row[];records:Record<string,ContactDraft>}[]>([]),[notice,setNotice]=useState(''),[linked,setLinked]=useState(''),[detail,setDetail]=useState('');
 useEffect(()=>{const f=()=>setPath(location.pathname);window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f);},[]);
 useEffect(()=>{sessionStorage.setItem('mock-db-rows',JSON.stringify(rows));},[rows]);
 useEffect(()=>{localStorage.setItem('mock-db-v3-columns',JSON.stringify(visible));},[visible]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id);},[notice]);
 function change(next:Row[],message='저장했습니다'){setUndo(u=>[...u,{rows,records}]);setRows(next.map(r=>({...r,phone:formatPhone(r.phone)})));setNotice(message);}
 function edit(id:string,key:Key,value:string){change(rows.map(r=>r.id===id?(key==='result'?recordContact(r,value,'2026-10-10'):{...r,[key]:value}):r));}
 function updateContact(id:string,value:ContactDraft){setUndo([]);setRecords(prev=>({...prev,[id]:{...value,place:value.ci.소재지||''}}));}
 function register(id:string){const r=rows.find(r=>r.id===id);if(!r)return;const d=records[id]||contactDraft(r);if(d.registered||!validDate(d.date)||!validDate(d.meetingDate)||!d.time||!d.ci.소재지?.trim())return;updateContact(id,{...d,registered:true});change(rows.map(v=>v.id===id?{...recordContact(v,'컨택진행',d.date),stage:['미컨택','상담 중','미팅예약'].includes(v.stage)?'미팅예약':v.stage}:v),'미팅카드를 등록했습니다. 컨택관리에서도 확인할 수 있습니다.');}
 function openContact(id=''){setLinked(id);setDetail('');navigate('/contact');}
 const filtered=rows.filter(r=>(!search||[r.company,r.owner,r.phone].some(x=>x.includes(search)))&&(!supplier||r.supplier===supplier)&&(!from||r.date>=from)&&(!to||r.date<=to));
 const sheet=path==='/db-sheet',contact=path==='/contact',selected=rows.find(r=>r.id===detail),activeFilters=!!(search||supplier||from||to);
 return <DirtyProvider><div className="desktop-shell pc:flex" onClickCapture={e=>{const a=(e.target as HTMLElement).closest('a');if(a&&new URL(a.href,location.href).origin!==location.origin){e.preventDefault();e.stopPropagation();setNotice('미리보기에서는 외부 페이지를 열지 않습니다.');}}}><DesktopNav/><div className="min-w-0 pc:flex-1"><main className="app-shell-main"><TopHeader pageEmoji={sheet?'📋':contact?'📞':'📊'} pageTitle={sheet?'DB관리시트':contact?'컨택관리':'DB생산'} pageSubtitle={sheet?'받은 DB를 정리하고, 진행상황을 한눈에':contact?'업체별 연락과 상담 기록':'영업의 시작, DB생산'}/><PageContainer width="fluid" className="sheet-page px-3 py-3 pb-28">
 <div className="sheet-subnav"><div><button className={path==='/db'?'active':''} onClick={()=>navigate('/db')}>DB생산</button><button className={sheet?'active':''} onClick={()=>navigate('/db-sheet')}>DB관리시트</button></div><span className="preview-label">미리보기 v0.31 · 예시 데이터</span></div>
 {sheet?<section className="sheet-panel db-sheet-panel">
 <div className="sheet-panel-head"><div><h2>DB 목록 <span>{rows.length}</span></h2></div><div className={`sheet-filters ${filtersOpen?"filters-open":""}`}><input aria-label="DB 검색" className="sheet-input search" placeholder="사업자명, 대표자, 전화번호 검색" value={search} onChange={e=>setSearch(e.target.value)}/><button className="sheet-btn sheet-filter-toggle" aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}>필터{(supplier||from||to)?" •":""}</button><select aria-label="공급처 필터" className="sheet-input" value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">전체 공급처</option>{[...new Set(rows.map(r=>r.supplier))].map(v=><option key={v}>{v}</option>)}</select><div className="sheet-dates"><span>유입일</span><input className="sheet-input" type="date" aria-label="유입 시작일" value={from} onInput={e=>setFrom(e.currentTarget.value)} onChange={e=>setFrom(e.target.value)}/><span>~</span><input className="sheet-input" type="date" aria-label="유입 종료일" value={to} onInput={e=>setTo(e.currentTarget.value)} onChange={e=>setTo(e.target.value)}/></div>{activeFilters&&<button className="sheet-text-btn" onClick={()=>{setSearch('');setSupplier('');setFrom('');setTo('');}}>초기화</button>}<div className="sheet-table-tools" title="셀 클릭 수정 · 제목을 끌어 열 이동 · 경계를 끌어 너비/높이 조절">{activeFilters&&<span>{filtered.length}건</span>}<div><button className="sheet-text-btn" disabled={!undo.length} onClick={()=>{setRows(undo[undo.length-1]!.rows);setRecords(undo[undo.length-1]!.records);setUndo(undo.slice(0,-1));setNotice('직전 변경을 되돌렸습니다.');}}>↶ 되돌리기</button><button className="sheet-btn" aria-expanded={settings} onClick={()=>setSettings(!settings)}>표시할 열</button></div></div></div><div className="sheet-add-actions"><button className="sheet-btn" onClick={()=>setDraft({...blank(),date:"2026-10-10"})}>＋ 직접 입력</button><button className="sheet-btn primary" onClick={()=>setImporting(true)}>DB 가져오기</button></div></div>
 {draft&&<form className="sheet-direct-form" onSubmit={e=>{e.preventDefault();if(!draft.company.trim()||!validDate(draft.date))return;change([{...draft,company:draft.company.trim()},...rows],"업체를 추가했습니다. 컨택관리에도 표시됩니다.");setDraft(null);setSearch("");setSupplier("");setFrom("");setTo("");}}><strong>새 업체 입력</strong><div>{(["company","owner","phone","supplier","date"] as Key[]).map(k=><label key={k}>{columns.find(c=>c.key===k)?.label}<input autoFocus={k==="company"} className="sheet-input" aria-label={`직접 입력 ${columns.find(c=>c.key===k)?.label}`} type={k==="date"?"date":"text"} required={k==="company"||k==="date"} value={draft[k]} onInput={e=>setDraft({...draft,[k]:e.currentTarget.value})} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}</div><footer><span>나머지 정보는 추가 후 표에서 입력하세요.</span><button type="button" className="sheet-btn" onClick={()=>setDraft(null)}>취소</button><button type="submit" className="sheet-btn primary" disabled={!draft.company.trim()||!validDate(draft.date)}>추가</button></footer></form>}

 {settings&&<div className="sheet-column-settings"><strong>필요한 정보만 표시하세요</strong><div>{columns.map(c=><label key={c.key}><input type="checkbox" checked={visible.includes(c.key)} onChange={e=>setVisible(e.target.checked?[...visible,c.key]:visible.filter(k=>k!==c.key))}/>{c.label}</label>)}</div><button className="sheet-text-btn" onClick={()=>{setVisible([...defaults]);window.dispatchEvent(new Event('mock-db-reset-view'));}}>기본 8개 열로 되돌리기</button></div>}
 <Grid rows={filtered.map(r=>({...r,memo:(records[r.id]?.note||'').split(/\r?\n/)[0]||''}))} visible={visible} fail={false} onDetail={setDetail} onOpen={setDetail} onChange={edit}/><div className="sheet-panel-foot"><span>최초상담일과 현재상태는 영업 기록에서 자동 반영됩니다.</span><span>총 {filtered.length}건</span></div>
 </section>:contact?<ContactDemo onName={(id,v)=>edit(id,"company",v)} records={records} onRecord={updateContact} onRegister={register} rows={rows} linked={linked} onBack={()=>navigate('/db-sheet')} onUpdate={(id,result,date)=>change(rows.map(r=>r.id===id?recordContact(r,result,date):r),'상담 기록을 저장했습니다. DB시트에도 반영됩니다.')} onAdd={row=>change([...rows,row],'새 업체를 추가했습니다.')}/>:<section className="sheet-panel sheet-placeholder"><h2>DB생산</h2><p>DB관리시트는 별도 페이지로 사용하는 보조 도구입니다.</p><button className="sheet-btn primary" onClick={()=>navigate('/db-sheet')}>DB관리시트 열기</button><button className="sheet-btn" onClick={()=>openContact()}>컨택관리 열기</button></section>}
 <footer className="sheet-preview-footer"><span>합성 데이터 목업 · 실제 영업 기록은 바뀌지 않습니다.</span><button onClick={()=>{setRows(initial);setRecords({});setUndo([]);setNotice('예시 데이터를 복원했습니다.');}}>예시 복원</button></footer></PageContainer></main></div><TabBar/></div>
 {notice&&<div role="status" className="sheet-toast">✓ {notice}</div>}
 {selected&&<DbDetail key={selected.id} row={selected} draft={records[selected.id]||contactDraft(selected)} onChange={v=>updateContact(selected.id,v)} onEdit={(k,v)=>edit(selected.id,k,v)} onResult={(v,date)=>{if(validDate(date))change(rows.map(r=>r.id===selected.id?recordContact(r,v,date):r));}} onRegister={()=>register(selected.id)} onOpen={()=>openContact(selected.id)} onClose={()=>setDetail('')}/>}

 {importing&&<ImportDialog rows={rows} onClose={()=>setImporting(false)} onApply={added=>{change([...added,...rows],`${added.length}개 업체를 추가했습니다. 컨택관리에도 표시됩니다.`);setImporting(false);}}/>}</DirtyProvider>;
}
createRoot(document.getElementById('root')!).render(<App/>);
