import {context} from 'esbuild';
import {readFileSync,readdirSync,mkdtempSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createServer} from 'node:http';
import {spawnSync} from 'node:child_process';
const dir=mkdtempSync(join(tmpdir(),'db-sheet-mockup-'));
const nav=`import React,{useSyncExternalStore} from 'react';const subscribe=f=>{window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)};export const usePathname=()=>useSyncExternalStore(subscribe,()=>location.pathname);export const go=p=>{if(!p.startsWith('/')||p.startsWith('//'))return;history.pushState({},'',p);window.dispatchEvent(new PopStateEvent('popstate'))};export const useRouter=()=>({push:go,replace:go,refresh:()=>{}});export const useSearchParams=()=>new URLSearchParams(location.search);export default function Link({href,children,onClick,...p}){return <a {...p} href={href} onClick={e=>{e.preventDefault();if(onClick)onClick(e);else go(String(href))}}>{children}</a>}`;
const mocks={
 './company-doc/CompanyDocAutofillButton':`export default function MockDoc(){return null;}`,
 './company-info/CompanyVaultSection':`export default function MockVault(){return null;}`,

 '@/query/me-hook':`export const useMe=()=>({data:{name:'연습사용자',cohort:'샘플',email:'mock@example.invalid',sessionRole:'student'},isLoading:false});`,
 '@/query/announcements-hook':`export const useAnnouncements=()=>({data:{latestPr:0,announcements:[],activeAnchor:null}});`,
 '@/analytics':`export const identifyUser=()=>{};export const resetUser=()=>{};export const markInternal=()=>{};export const clearInternal=()=>{};`,
 'next-auth/react':`export const signOut=()=>{};`,
};
const ctx=await context({entryPoints:['tests/browser/db-sheet/App.tsx'],bundle:true,outfile:join(dir,'app.js'),platform:'browser',jsx:'automatic',define:{'process.env':'{}','process.env.NODE_ENV':'"development"'},plugins:[{name:'isolated-mock',setup(b){
 b.onResolve({filter:/.*/},args=>{if(mocks[args.path])return {path:args.path,namespace:'mock'};if(/^next\/(link|navigation)$/.test(args.path))return{path:'navigation',namespace:'mock'};if(args.path.endsWith('auth/RoleViewSwitch'))return{path:'role',namespace:'mock'};if(args.path.endsWith('announcements/AnnouncementsGate'))return{path:'ann',namespace:'mock'};});
 b.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:args.path==='navigation'?nav:args.path==='role'?`export default function RoleViewSwitch(){return null};export const useTrainerState=()=>({data:{canStudent:true,canTrainer:false}});`:args.path==='ann'?`export const ANNOUNCEMENTS_SEEN_EVENT='mock-ann';export const hasUnseenUpdates=()=>false;export default function AnnouncementsGate(){return null};`:mocks[args.path],loader:'tsx',resolveDir:process.cwd()}));
 b.onLoad({filter:/company-info-defs\.ts$/},args=>({contents:readFileSync(args.path,'utf8').replace(/^.*f\(\["(?:업체|대표)기타메모".*\r?\n/gm,''),loader:'ts',resolveDir:resolve('components')}));
 b.onLoad({filter:/DesktopNav\.tsx$/},args=>({contents:readFileSync(args.path,'utf8').replace('import { BookOpen,', 'import { Table2, BookOpen,').replace('active={tab.match(pathname)}','active={tab.match(pathname) && pathname !== "/db-sheet"}').replace(/            <\/SideLink>\r?\n          <\/div>/,'            </SideLink>\n{tab.href === "/db" && <SideLink compact={collapsed} href={"/db-sheet" as Route} active={pathname === "/db-sheet"} label="STEP 1.5 DB관리시트" activeClass="bg-blue-50 font-semibold text-blue-700"><span className="db-nav-icon-wrap"><Table2 className="db-nav-icon" aria-hidden="true"/>{collapsed && <span className="db-step-mini">1.5</span>}</span>{!collapsed && <><span className="db-step-badge">STEP 1.5</span><span className="db-nav-label">DB관리시트</span></>}</SideLink>}\n          </div>'),loader:'tsx',resolveDir:resolve('components/desktop')}));
 }}]});await ctx.rebuild();await ctx.watch();
const css=spawnSync(process.execPath,['node_modules/tailwindcss/lib/cli.js','-i','app/globals.css','-o',join(dir,'style.css'),'--content','app/**/*.{ts,tsx},components/**/*.{ts,tsx},tests/browser/db-sheet/**/*.{ts,tsx}'],{encoding:'utf8'});if(css.status!==0)throw new Error(css.stderr);
const built=readdirSync('.next/static/css').filter(f=>f.endsWith('.css')).map(f=>readFileSync(join('.next/static/css',f),'utf8')).join('\n');
const faces=(built.match(/@font-face\{[^}]+\}/g)||[]).filter(s=>s.includes('Noto')).join('\n');const family=faces.match(/font-family:([^;]+);/)?.[1];if(!family)throw new Error('Run npm run build first for production fonts');const fontCss=faces.replaceAll('../media/','/media/').replaceAll('/_next/static/media/','/media/')+`:root{--font-noto-sans-kr:${family}}`;
const media=new Map(readdirSync('.next/static/media').map(f=>['/media/'+f,join('.next/static/media',f)]));
const html='<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DB관리시트 · 합성 목업</title><link rel="stylesheet" href="/font.css"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/mock.css"><body class="min-h-dvh bg-slate-50 font-sans text-slate-900 antialiased"><div id="root"></div><script src="/app.js"></script></body></html>';
const server=createServer((req,res)=>{const path=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Security-Policy',"default-src 'self'; connect-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; form-action 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'");res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.writeHead(405);return res.end('Mock server: writes disabled');}const files={'/app.js':join(dir,'app.js'),'/style.css':join(dir,'style.css'),'/mock.css':'tests/browser/db-sheet/mock.css','/salespt-logo.png':'public/salespt-logo.png'};if(path==='/font.css'){res.setHeader('Content-Type','text/css');return res.end(fontCss);}if(files[path]||media.has(path)){res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.png')?'image/png':'font/woff2');return res.end(readFileSync(files[path]||media.get(path)));}if(path.startsWith('/api/')||path.startsWith('/auth/')){res.writeHead(403);return res.end('Production API disabled in mockup');}if(['/','/db-sheet','/db','/contact','/dashboard','/calendar','/schedule','/payment','/weekly-goals'].includes(path)){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html);}res.writeHead(404);res.end('Mock route not implemented');});
server.listen(0,'127.0.0.1',()=>console.log(`MOCKUP_URL=http://127.0.0.1:${server.address().port}/db-sheet`));
